version: "3"
services:
<<<<<<< HEAD
    web:
=======
    test:
>>>>>>> master
        build:
            context: .
            dockerfile: Dockerfile-test
        depends_on:
<<<<<<< HEAD
=======
            - app
    app:
        build: ./ucubot
        ports:
            - "80"
        depends_on:
>>>>>>> master
            - db
    db:
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: "1qaz2wsx"
            ACCEPT_EULA: "Y"
